#!/bin/bash

cd $HOME
wget http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.11.2.tar.gz
tar -xvf petsc-3.11.2.tar.gz
mkdir -p $HOME/local
cd petsc-3.11.2
./configure CPP=/usr/bin/cpp COPTFLAGS='-O3 -march=native -mtune=native' CXXOPTFLAGS='-O3 -march=native -mtune=native' \
            --prefix=$HOME/local/petsc \
            --with-mpi=1 --with-mpi-dir=/act/openmpi-2.0/gcc-8.2.0 \
            --with-cxx-dialect=c++11 \
            --with-metis=1 --download-metis=yes \
            --download-metis-shared=0 \
            --with-parmetis=1 --download-parmetis=yes \
            --download-parmetis-shared=0 \
            --with-hypre=1 --download-hypre=yes \
            --download-hypre-shared=0 \
            --with-blaslapack=1 \
            --with-blaslapack-dir=/opt/intel/mkl \
            --with-zlib=1 \
            --with-ml=1 --download-ml=yes \
            --download-ml-shared=0 \
            --with-cmake=1 \
            --with-shared-libraries \
            --download-sowing-cc=gcc \
            --download-sowing-cxx=g++ \
            --download-sowing-cxxcpp=cpp \

make PETSC_DIR=$HOME/petsc-3.11.2 PETSC_ARCH=arch-linux2-c-debug all            
export LD_LIBRARY_PATH=$COMMON_INSTALL_DIR/lib:$PETSC_DIR/lib:/opt/intel/mkl/lib/intel64:$LD_LIBRARY_PATH

