#!/bin/env bash

# This script installs Netgen/Ngsolve for serial processing
# assuming that Python3 and Cmake3 are already installed

module load gcc-9.2.0
module load intel-18.0

export BASEDIR=$HOME/NGserial
export BUILDDIR=$BASEDIR/build
export SRCDIR=$BASEDIR/ngsolve

if [ ! -d $SRCDIR ]; then
    mkdir -p $BASEDIR 
    cd $BASEDIR && git clone https://github.com/NGSolve/ngsolve.git ngsolve
fi

cd $SRCDIR
git submodule update --init --recursive
if [ -d $BUILDDIR ]; then
   rm -rf $BUILDDIR
fi
mkdir -p $BUILDDIR 
cd $BUILDDIR

if [ $CLUSTER == "GAIA" ]; then
cmake \
  -DCMAKE_INSTALL_PREFIX=$BASEDIR \
  -DMKL_ROOT=/vol/apps/compilers/intel/2018/compilers_and_libraries_2018.1.163/linux/mkl \
  -DUSE_MKL=ON \
  -DUSE_UMFPACK=ON \  # still can't find pardiso on Gaia
  -DCMAKE_BUILD_TYPE=Release \
  $BASEDIR/ngsolve
else
cmake \
  -DCMAKE_INSTALL_PREFIX=$BASEDIR \
  -DMKL_ROOT=/opt/intel/mkl \
  -DUSE_MKL=ON \
  -DUSE_PARDISO=ON \
  -DUSE_UMFPACK=ON \
  -DCMAKE_BUILD_TYPE=Release \
  $BASEDIR/ngsolve
fi
# Note: seg faults are possible with both MKL and UMFPACK on

make -j20
make install

