#! /usr/bin/bash
if [ "$1" = "" ]; then
    echo "Please specify the desired version, e.g. 3.7.2"
    exit 1
fi

# Install the specified version of Python3
# in the common subdirectory of the user's home directory
BASE_DIR=$HOME
export SRC_DIR=$BASE_DIR/common/src
export INSTALL_DIR=$BASE_DIR/common/install
mkdir -p $INSTALL_DIR
mkdir -p $SRC_DIR

PYTHON_VER_NO=$1
PYTHON_VERSION=Python-$PYTHON_VER_NO
cd $SRC_DIR
wget https://www.python.org/ftp/python/$PYTHON_VER_NO/$PYTHON_VERSION.tgz
tar xvf Python-$PYTHON_VER_NO.tgz
export BUILD_DIR=$SRC_DIR/$PYTHON_VERSION/build
mkdir -p $BUILD_DIR && cd $BUILD_DIR
../configure --prefix=$INSTALL_DIR --enable-shared
make -j10
make install

# You may want to do this sort of thing...
#pip3 install numpy scipy matplotlib sympy ipython3
# etc ...

