#!/bin/env bash

# This script installs Netgen/Ngsolve for serial processing
# assuming that Python3 and Cmake3 are already installed

module load gcc-9.2.0
# module load intel-18.0

export BASEDIR=$HOME/NGserial
export BUILDDIR=$BASEDIR/build
export SRCDIR=$BASEDIR/ngsolve

if [ ! -d $SRCDIR ]; then
    mkdir -p $BASEDIR 
    cd $BASEDIR && git clone https://github.com/NGSolve/ngsolve.git ngsolve
fi

cd $SRCDIR
git submodule update --init --recursive
if [ -d $BUILDDIR ]; then
   rm -rf $BUILDDIR
fi
mkdir -p $BUILDDIR 
cd $BUILDDIR
cmake \
  -DCMAKE_INSTALL_PREFIX=$BASEDIR \
  -DUSE_UMFPACK=ON \
  -DCMAKE_BUILD_TYPE=Release \
  $BASEDIR/ngsolve

#  -DUSE_MKL=ON \
#  -DMKL_ROOT=/opt/intel/mkl \ # bad path and seems we do not need this
#  -DUSE_UMFPACK=ON \   # possible seg faults with both MKL and UMFPACK on
#  -DUSE_PARDISO=ON \   # can't find pardiso on Gaia

make -j20
make install

# Test that everything works
# $ cd $BASEDIR/ngsolve/py_tutorials
# $ netgen poisson.py
