#! /usr/bin/bash

# This script installs Netgen/Ngsolve for serial processing
# assuming that Python3 and Cmake3 are already installed

module load gcc-9.2.0

export BASEDIR=$HOME/NGserial
mkdir -p $BASEDIR
cd $BASEDIR && git clone https://github.com/NGSolve/ngsolve.git ngsolve
cd $BASEDIR/ngsolve
git submodule update --init --recursive
git submodule sync --recursive
git submodule update --init --recursive

mkdir $BASEDIR/build 
cd $BASEDIR/build
cmake \
  -DCMAKE_INSTALL_PREFIX=$BASEDIR \
  -DUSE_MKL=ON \
  -DUSE_UMFPACK=ON \
  -DMKL_ROOT=/opt/intel/mkl \
  -DCMAKE_BUILD_TYPE=Release \
  $BASEDIR/ngsolve

make -j20
make install

# Test that everything works
# $ cd $BASEDIR/ngsolve/py_tutorials
# $ netgen poisson.py
