#!/bin/bash

module load gcc-9.2.0
module load intel
module load ngsolve/phi_serial

export BASEDIR=$HOME/NGserialPhi
cd $BASEDIR
git clone https://github.com/NGSolve/ngs-special-functions.git
cd ngs-special-functions
mkdir build && cd build
cmake ..
# automatically installs during build to your NGSolve installation
make -j10 
