#!/bin/env bash

module load gcc-9.2.0
module load ngsolve/serial

if [ $CLUSTER == "GAIA" ]; then
	module load intel-18.0
else
	module load intel
fi

export BASEDIR=$HOME/NGserial
cd $BASEDIR
git clone https://github.com/NGSolve/ngs-special-functions.git
cd ngs-special-functions
mkdir build && cd build
cmake ..
# automatically installs during build to your NGSolve installation
make -j10 
