#! /usr/bin/bash
source use_serial
export BASEDIR=$HOME/NGserial
cd $BASEDIR
git clone https://github.com/NGSolve/ngs-special-functions.git
cd ngs-special-functions
mkdir build && cd build
cmake ..
# automatically installs during build to your NGSolve installation
make -j10 
