#! usr/bin/bash

# Install the current versions of Python3 and Cmake3
# in the user's home directory (by default)
BASE_DIR=$HOME

PYTHON_VER_NO=3.6.5
PYTHON_VERSION=Python-$PYTHON_VER_NO
export INSTALL_DIR=$BASE_DIR/common/python3
export BUILD_DIR=$INSTALL_DIR/$PYTHON_VERSION/build
mkdir -p $INSTALL_DIR && cd $INSTALL_DIR
wget https://www.python.org/ftp/python/$PYTHON_VER_NO/$PYTHON_VERSION.tgz
tar xvf Python-$PYTHON_VER_NO.tgz
cd $INSTALL_DIR/$PYTHON_VERSION
mkdir -p $BUILD_DIR
cd $BUILD_DIR
../configure --prefix=$INSTALL_DIR --enable-shared
make -j10
make install

CMAKE_MAJ_NO=3.11
CMAKE_VER_NO=3.11.3
CMAKE_VERSION=cmake-$CMAKE_VER_NO
export INSTALL_DIR=$BASE_DIR/common/cmake3
export BUILD_DIR=$INSTALL_DIR/$CMAKE_VERSION/build
mkdir -p $INSTALL_DIR && cd $INSTALL_DIR
wget https://cmake.org/files/v$CMAKE_MAJ_NO/$CMAKE_VERSION.tar.gz
tar xvf $CMAKE_VERSION.tar.gz
cd $INSTALL_DIR/$CMAKE_VERSION
mkdir -p build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
make -j10
make install

# You may want to do this sort of thing...
#pip3 install numpy scipy matplotlib sympy ipython3
# etc ...

