#! usr/bin/bash

# Install the current versions of Python3 and Cmake3
export INSTALL_DIR=$HOME/common/python3
mkdir -p $INSTALL_DIR && cd $INSTALL_DIR
wget https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz
tar xvf Python-3.6.5.tgz
cd $INSTALL_DIR/Python-3.6.5
mkdir -p build
cd build
../configure --prefix=$INSTALL_DIR --enable-shared
make -j10
make install

export INSTALL_DIR=$HOME/common/cmake3
mkdir -p $INSTALL_DIR && cd $INSTALL_DIR
wget https://cmake.org/files/v3.11/cmake-3.11.3.tar.gz
tar xvf cmake-3.11.3.tar.gz
cd $INSTALL_DIR/cmake-3.11.3
mkdir -p build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
make -j10
make install

# You may want to do this sort of thing...
pip3 install numpy scipy matplotlib sympy ipython3
# etc ...

