#!/usr/bin/bash
# Slurm Example from Jay, modified for consistency with the other scripts here.
# Note: The pound signs in front of the SBATCH commands are necessary.
# Note: This assumes you have specified to use the serial installation 
#  of NGSolve by placing 'source use_serial' in your .bashrc or executing it
#  manually.

#SBATCH --job-name run_p2_L7_n500
#SBATCH --nodes=1                    # Use one node
#SBATCH --ntasks=1                   # Run a single task       
#SBATCH --cpus-per-task=20           # Number of CPU cores per task
#SBATCH --output=outputs/run_p2_L7_n500.log


pwd; hostname;
echo "Starting at wall clock time:"
date
echo "Running CMT on $SLURM_CPUS_ON_NODE CPU cores"

export PYTHONPATH=$HOME/fiberamp:$PYTHONPATH

export OMP_NUM_THREADS=20

module load gcc-9.2.0
module load ngsolve/serial

python3 $HOME/fiberamp/cmt/run_p2_L7_n500.py

echo "Ending at wall clock time:"
date


