#! /usr/bin/bash
export BASEDIR=$HOME/NGserial
module load gcc-9.2.0
module load intel
module load ngsolve/serial

cd $BASEDIR/ngs-special-functions
git pull
rm -rf build && mkdir build && cd build
cmake ..
# automatically installs during build to your NGSolve installation
make -j10 
