#! /usr/bin/bash
export BASEDIR=$HOME/NGserialPhi
module load gcc-8.2.0
module load intel
module load ngsolve/phi_serial

cd $BASEDIR/ngs-special-functions
git pull
rm -rf build && mkdir build && cd build
cmake ..
# automatically installs during build to your NGSolve installation
make -j10 
