#! /usr/bin/bash

# to set up for parallel ngsolve with openmpi, source this file like this:
# source use_parallel (or like this: . use_parallel)

export NETGENDIR=$HOME/NGparallel/bin
export PATH=$NETGENDIR:$PATH
export LD_LIBRARY_PATH=$NETGENDIR/../lib:$LD_LIBRARY_PATH
export PYTHONPATH=$NETGENDIR/../`python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1,0,''))"`:$PYTHONPATH

# Test that everything works
#cd $NETGENDIR/../ngsolve/py_tutorials/mpi
#mpirun -np 5 ngspy mpi_poisson.py

# This should generate a directory poisson_output 
# with some nonempty vtk files.
