#! /usr/bin/bash
# source this file to set up for serial ngsolve like this:
# source use_serial (or like this: . use_serial)

export NETGENDIR=$HOME/NGserial/bin
export PATH=$NETGENDIR:$PATH
export LD_LIBRARY_PATH=$NETGENDIR/../lib:$LD_LIBRARY_PATH
export PYTHONPATH=$NETGENDIR/../`python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1,0,''))"`:$PYTHONPATH

# Test that everything works
#cd $NETGENDIR/../ngsolve/py_tutorials
#netgen poisson.py
